# Site settings
title: Your Ski Concierge
email: nski@productteams.com
description: > # this means to ignore newlines until "baseurl:"
  Your ski concierge that makes getting to the slopes a much more
  enjoyable experience. VIP level service that takes the hassle
  out of skiing and gives a better mountain playground experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nski.co" # the base hostname & protocol for your site
twitter_username: nski
github_username:  productteams

# Build settings
markdown: kramdown
